{% set version = "0.9.11" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-flowr
  version: {{ version|replace("-", "_") }}

source:
  fn: flowr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/flowr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/flowr/flowr_{{ version }}.tar.gz
  sha256: 25fe3fb85b20442d9c24658609a0a4c3dabdfae37203e1e1da94e1ff76766bb1

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-diagram
    - r-params >=0.3
    - r-whisker

  run:
    - r-base
    - r-diagram
    - r-params >=0.3
    - r-whisker

test:
  commands:
    - $R -e "library('flowr')"  # [not win]
    - "\"%R%\" -e \"library('flowr')\""  # [win]

about:
  home: https://github.com/sahilseth/flowr
  license: MIT
  summary: This framework allows you to design and implement complex pipelines, and deploy them on your institution's computing cluster. This has been built keeping in mind the needs of bioinformatics workflows. However, it is easily extendable to any field where a series of steps (shell commands) are to be executed in a
    (work)flow.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
