{% set version = '0.9.11' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-flowr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/flowr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/flowr/flowr_{{ version }}.tar.gz
  sha256: 25fe3fb85b20442d9c24658609a0a4c3dabdfae37203e1e1da94e1ff76766bb1

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-diagram
    - r-params >=0.7
    - r-readr
    - r-whisker
  run:
    - r-base
    - r-diagram
    - r-params >=0.7
    - r-readr
    - r-whisker

test:
  commands:
    - $R -e "library('flowr')"           # [not win]
    - "\"%R%\" -e \"library('flowr')\""  # [win]

about:
  home: https://github.com/flow-r/flowr
  license: MIT
  summary: This framework allows you to design and implement complex pipelines, and deploy them
    on your institution's computing cluster. This has been built keeping in mind the
    needs of bioinformatics workflows. However, it is easily extendable to any field
    where a series of steps (shell commands) are to be executed in a (work)flow.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: flowr
# Type: Package
# Title: Streamlining Design and Deployment of Complex Workflows
# Description: This framework allows you to design and implement complex pipelines, and deploy them on your institution's computing cluster. This has been built keeping in mind the needs of bioinformatics workflows. However, it is easily extendable to any field where a series of steps (shell commands) are to be executed in a (work)flow.
# Version: 0.9.11
# Depends: R (>= 3.3), methods, params (>= 0.7), utils
# Imports: diagram, whisker, tools, readr
# Suggests: reshape2, knitr, testthat, funr, rmarkdown
# Enhances: ggplot2, openxlsx, pacman, cowplot
# VignetteBuilder: knitr
# URL: https://github.com/flow-r/flowr
# BugReports: https://github.com/flow-r/flowr/issues
# Authors@R: c(person("Sahil", "Seth", role = c("aut", "cre"), email = "me@sahilseth.com"))
# License: MIT + file LICENSE
# RoxygenNote: 7.1.1
# Language: en-US
# NeedsCompilation: no
# Packaged: 2021-03-02 21:43:35 UTC; sahilseth
# Author: Sahil Seth [aut, cre]
# Maintainer: Sahil Seth <me@sahilseth.com>
# Repository: CRAN
# Date/Publication: 2021-03-02 22:00:03 UTC
