travis:
  secure:
    BINSTAR_TOKEN: S9Ip7EkufvPzYZAPSo9UC9Taqzhcqg5NuxTR7na1do36piZDDbn51sSo9uwhIRTehYsnR+5rZNAoU1bt9ZR198aByu6hGPpl5Y9nG3StEqaXRESRDXB5ng5J4yjIdDWkncHDIcZS9pzoZOakr/f+t9nUyCclB2/vbBhdrxKF/lBbmjZk8zpAcMIq9bTLzFb7aKt2Ft/Je7jzJgsE5SOZwP9sd+Yd6ILmWqFkpCkamK5zfby5QwuaSLVEra1KZWfxYbvQAW4AH+0ZQkRgvPBT+hkudCp4FlnxV88DrocmFHbN4qoOlZhCCZki2UJfR+JPKxz4A9LzY1pAsYtyBG592+/sIrAzmLTpS/7dg+OS68LgvwfDvjbsoCx1RSQL1zhe7V2yC9HKuJ445Ikkt35f1rX/ekrCm9h0G9lLcRyPRWfSQCXyJJj3cc8qMX2XaXY/kkzxfB+G9PSJ59n/yeRIH0+gAQtyqNts3uYCG17mB/LZDwqPi+FGeacLbwllCXw96LPv7mJ43mb7PuyXMTn68IqtC4yA7+o3Ok9wDj4VxvQtgv+4NtnzQB+L+xBH0dTG1xZ6R3DBrXJfsfyg9iZfUZEW5wWfMIUlVyzYAWaLTmrqJNPKHxf8kBL/0aCFp5GMN0xRG2DCEh9Y0024aPMx2KW51OM6q1wPzNWxXeTnXy8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
