travis:
  secure:
    BINSTAR_TOKEN: duMu87B+tFVuihZ0hYue6vmJGbmtkDUYXAHW0HHivFRC+1kn4E4uJ81JQtGfEuEIjdjKdncCKQpjGT31MusuOqPeytzGYkpqMTaPVFLqxTJTncJtomHVL0rtVdHTIPf7ov8Fny8u24/A3t2u6kJ+Ay5jUv4jB3cuSC3MIuxqGYzrOmZwZbedbiq08cwOrO15CBS5pB8F4ugMC3MLeH8gaU/l9KudvlneAR7EjIhtnYoJMl63sY/7XWc8ibkXtrLv3j89jt+2PkNRKei2CEuAxUmkEb2qai99hBDHt1/bMjIaQ7HG+1i0DizUivzwD6w/ZCCNcu8QCaUSrvkcy/9wzDt0fu5O7G8VvDlpZ2Oj6GFwUGZ2Xf0iABobFLpZxdhb69yt4Utq6APnAC8ZB7g2mVB8iLXeWrHc2i3yXQulxIjrUzO56tVOnW9NpaVOSj86TFZRixkSfBi76wQsOX/B0UmHBnN/O9HOOwAsUPpvh4EzFbIgp6jB30G4gkkJPbPDb2UWj57qPbdaPQVfoLtU4wjbGoPaGOxFRv/5/ZV9hRD9GUjyB+g2LaAJRDzV0wRln5X9FO8c6c8ZecnTgPzV4JffFl7SI6Hy8Ocykmpw+dGqZ3mS3KkcAeelzTQRG1/kaHwT5dL20o5inmlc7dvLVIzgQMoC6hx1+w3K0ThsaLU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
